// 'use client'

import { APP_ROUTES } from '@/constants/app-routes'
import { useCookies } from '@/hooks/useCookies'
import { useRouter } from 'next/navigation'
import { useEffect } from 'react'

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function PrivateRoute({
  children,
}: {
  children: React.ReactNode
}) {
  const { push } = useRouter()
  const { isAuthenticated } = useCookies()
  // ver uma maneira de ver se está autenticado pois o valor do hook sempre vem primeiro
  // o valor padrão (flase) e isso impede aa navegação pois entra dentro do if abaixo

  useEffect(() => {
    if (isAuthenticated === false) {
      console.log('pr', isAuthenticated)
      push(APP_ROUTES.public.EmptyHomePage)
    }
  }, [isAuthenticated, push])

  return (
    <>
      {!isAuthenticated && null}
      {isAuthenticated && children}
    </>
  )
}
